### ISSUE TITLE
make sure to suicide

### ISSUE THREAD

**Issue by IronException** [TheSocietyProject/DontTouchMyBot#2]
if for some reason u dont get killed there has to be a mechanism that checks that and rekills then.

**Comment by IronException** [comment]
there could be an extra thread that waits for 2 secs or sth and then checks the position. as long as they dont change kill again. Though if they r < then maybe 2 chunks or sth rekill cuz otherwise the bot could have been moved. -> while(dist(oldpos, nevpos) < 32) kill + wait(2 secs)

**Comment by TheSocietyProject** [comment]
fixed with a thread that waits still killed like suggested
